### ISSUE TITLE
Back End

### ISSUE THREAD

**Issue by HemaSAli** [FACG5/QuestionAndAnswer#4]
### Database Files
 - [ ] Db_Connection.js
 - [ ] Db_build.js
 - [ ] Db_build.js
------------------
### Server Files
- [ ] server.js
    - [ ] create server with its port and hots
- [ ] router.js 
    - [ ] routing home page
    - [ ] route to login page
    - [ ] route to Signup page
    - [ ] route 404 error page 
    - [ ] route getData from database
- [ ] handler.js
   - [ ] handling each routes
   - [ ] Check authentication  Method
-------------- 
### Testing 
 - [ ] Testing Database 
 - [ ] Testing server Functions
